# Generated by Django 5.1.2 on 2024-10-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notas',
            new_name='Nota',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='title',
            new_name='titulo',
        ),
    ]
